---
- hosts: all
  become: true
  vars_files:
    - default.yml
  tasks:
  - name: Update the machine
    command: sudo apt-get clean && update -y
    
  - name: Download docker installer 
    get_url: 
      url: https://get.docker.com 
      dest: get-docker.sh
    
  - name: Execute docker installer
    command: sudo sh get-docker.sh
      
  - name: Pull image for launching server
    docker_image:
      image: theironhidex/terraform-var:"{{ build_number }}"
      
  - name: Launch Container Image to Start Web Server
    docker_container:
      name: webserver
      image: theironhidex/terraform-var:"{{ build_number }}"
      state: started
      ports:
      - "80:80"
