---
- hosts: all
  become: true
  vars_files:
    - default.yml
  tasks:
  - name: Update the machine
    command: sudo apt-get clean && update -y
    
  - name: Install basic list of packages
    apt:
      name: ['ca-certificates','curl','gnupg','lsb-release']
      state: present
      update_cache: no
  - name: Add Docker GPG apt Key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg
  - name: Add Docker Repository
    apt_repository:
       repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
  - name: Install Docker packages
    apt:
       name: ['docker-ce','docker-ce-cli','containerd.io']
       state: present
  - name: Start service docker
    service:
      name: docker
      state: started
  - name: Create a web container
    docker_container:
      name: web
      image: theironhidex/terraform-var:"{{ build_number }}"
      ports:
      - "80:80"
