---
- hosts: all
  become: true
  vars_files:
    - default.yml
  tasks:
  - name: Update the machine
    command: sudo apt-get clean && update -y
    
  - name: Install basic list of packages
    apt:
      name: ['ca-certificates','curl','gnupg','lsb-release']
      state: present
      update_cache: no
    
  - name: Downloading Pre-Created Repository for Docker-ce
    get_url:
      url: https://download.docker.com/linux/rhel/docker-ce.repo
      dest: /etc/yum.repos.d/
      
  - name: Fixing Bug in the Repository.
    replace:
      path: /etc/yum.repos.d/docker-ce.repo
      regexp: 'rhel'
      replace: 'centos'
      
  - name: Installing Docker-ce.
    package:
      name: docker-ce
      state: present
  
  - name: Install docker SDK for Python
    pip:
      name: docker-py
      
  - name: Starting Docker Service.
    service:
      name: docker
      state: started
      enabled: yes
      
  - name: Pull image for launching server
    docker_image:
      image: theironhidex/terraform-var:"{{ build_number }}"
      
  - name: Launch Container Image to Start Web Server
    docker_container:
      name: webserver
      image: theironhidex/terraform-var:"{{ build_number }}"
      state: started
      ports:
      - "80:80"
